### PR TITLE
Additional Operations

### PR DESCRIPTION
**Pull request by jamesmcclain**
Additional local and focal operations have been added.

Connects #18

### CODE REVIEW

**Comment by caseypt** [comment]
Building this now to test with the app.

**Comment by caseypt** [comment]
I've tested a sample (about 10) of these functions with the app, and they all worked. From that perspective, +1. Nice job.

**Comment by jamesmcclain** [comment]
Okay, I will leave this open for a little while to see if anyone else wants to comment.  Thanks for reviewing.

**Comment by jamesmcclain** [comment]
If it is easier to work with, I can change the prefix from "LocalUnary" to "UnaryLocal".

**Comment by caseypt** [comment]
I think it'll work as is. Either way, we'll find a way to show them in the UI without `Unary`.

**Comment by jamesmcclain** [comment]
Okay, merging now ...

**Pull request merged**
