### PR TITLE
Include Static Configuration in .jar File

### PR DESCRIPTION
**Pull request by jamesmcclain**
The default layers and breaks are now registered automatically.

Connects #6

**To Test**
   * Type `./sbt assebmly` while in this branch to create a jar file
   * Transfer the new job file to the worker `scp ./target/scala-2.10/modellab-geoprocessing-assembly-0.4.0.jar vagrant@33.33.42.82:`
   * `ssh` to the worker and copy the jar file to `/opt/modellab-geoprocessing/`
   * Pull down this modellab branch: https://github.com/jamesmcclain/modellab/tree/feature/no-static-config and reprovision the worker on the branch
   * Optionally reload the worker
   * Try the site, it should behave as before
   * Also confirm that you can post layers and breaks to the service; that that capability still works

### CODE REVIEW

**Comment by caseypt** [comment]
Taking a look now.

**Comment by hectcastro** [comment]
Once this gets merged and released, I can amend https://github.com/azavea/modellab/pull/182 so that it works with these changes.

**Comment by jamesmcclain** [comment]
> Once this gets merged and released, I can amend azavea/modellab#182 so that it works with these changes.

Okay, sounds good

**Comment by caseypt** [comment]
When running the JAR with `spark-submit`, the layers and breaks are reportedly registered:

```
14:52:02 LayerRegistry: Register: CI4YRXI == LoadLayer(us-pennsylvania-philadelphia-nlcd2001-canopy-30m-epsg3857)
14:52:02 LayerRegistry: Register: CNFDKTA == LoadLayer(us-pennsylvania-philadelphia-census2010-block-popsqmi-30m-epsg3857)
14:52:02 LayerRegistry: Register: VU3XI2A == LoadLayer(us-pennsylvania-philadelphia-census2010-block-popsqmi-quantile-30m-epsg3857)
14:52:02 LayerRegistry: Register: 4E43KHA == LoadLayer(us-pennsylvania-philadelphia-census2010-block-totalpop-30m-epsg3857)
14:52:02 LayerRegistry: Register: A3ZL5GA == LoadLayer(us-pennsylvania-philadelphia-census2010-block-totalpop-quantile-30m-epsg3857)
14:52:02 LayerRegistry: Register: 34DWKUA == LoadLayer(us-pennsylvania-philadelphia-census2013-blockgroup-income-30m-epsg3857)
14:52:02 LayerRegistry: Register: LR3ARZA == LoadLayer(us-pennsylvania-philadelphia-census2013-blockgroup-income-quantile-30m-epsg3857)
14:52:02 LayerRegistry: Register: GVWWZ5Y == LoadLayer(us-pennsylvania-philadelphia-elevation-30m-epsg3857)
14:52:02 LayerRegistry: Register: YNVQ4BA == LoadLayer(us-pennsylvania-philadelphia-nlcd2001-impervious-30m-epsg3857)
14:52:02 LayerRegistry: Register: YVCGCIY == LoadLayer(us-pennsylvania-philadelphia-nlcd2011-impervious-30m-epsg3857)
14:52:02 LayerRegistry: Register: ENQM3KQ == LoadLayer(us-pennsylvania-philadelphia-nlcd2006-landcover-30m-epsg3857)
14:52:02 LayerRegistry: Register: XOEVAUA == LoadLayer(us-pennsylvania-philadelphia-nlcd2011-landcover-30m-epsg3857)
14:52:02 LayerRegistry: Register: MB3Q2YA == LoadLayer(us-pennsylvania-philadelphia-landsat-blue-30m-epsg3857)
14:52:02 LayerRegistry: Register: KRHNKAY == LoadLayer(us-pennsylvania-philadelphia-landsat-green-30m-epsg3857)
14:52:02 LayerRegistry: Register: COZ373Y == LoadLayer(us-pennsylvania-philadelphia-landsat-nir-30m-epsg3857)
14:52:02 LayerRegistry: Register: 3BWIPNI == LoadLayer(us-pennsylvania-philadelphia-landsat-red-30m-epsg3857)
14:52:02 LayerRegistry: Register: C2SO5IA == LoadLayer(nlcd-zoomed)
14:52:02 LayerRegistry: Register: 73O5S5Y == LoadLayer(us-pennsylvania-philadelphia-nlcd2011-reclass-30m-epsg3857)
14:52:02 LayerRegistry: Register: DC2TKBY == LoadLayer(us-pennsylvania-philadelphia-nlcd2011-trees-30m-epsg3857)
14:52:02 LayerRegistry: Register: MDIVHRI == LoadLayer(us-pennsylvania-philadelphia-nlcd2011-water-30m-epsg3857)
Registered Breaks: nlcd
Registered Breaks: tr
```

However, when I try to get a tile for a layer, I get a message like the following:

```
GET http://localhost:8888/tms/C2SO5IA/12/1193/1551.png?breaks=nlcd
```

```
geotrellis.spark.io.package$LayerReadError: LayerMetaData not found for layer Layer(name = "us-pennsylvania-philadelphia-landsat-nir-30m-epsg3857", zoom = 11)
```

**Comment by caseypt** [comment]
One sec. I think I may have figured it out.

**Comment by jamesmcclain** [comment]
> One sec. I think I may have figured it out.

Okay, sounds good.

**Comment by caseypt** [comment]
Okay. Figured it out. It was credentials issue when running the JAR outside the VM. I tested it fully within the VM and it worked as expected. Nice job. +1.

**Comment by jamesmcclain** [comment]
Okay, sounds good.  Thanks for reviewing.

**Pull request merged**
