### PR TITLE
Flatten "parameters" attribute into body of the operation definition

### PR DESCRIPTION
**Pull request by echeipesh**
This also re-orders the display of operation like so:

``` json
{
  "name": "LocalSubtract",
  "hash": "gXbYxA",
  "constant": null,
  "inputs": [{
    "name": "FocalMax",
    "hash": "sVOclQ",
    "neighborhood": {
      "size": 1,
      "shape": "square"
    },
    "inputs": [{
      "name": "LoadLayer",
      "hash": "NW1s9w",
      "layer_name": "us-pennsylvania-philadelphia-elevation-30m-epsg3857",
      "inputs": []
    }]
  }, {
    "name": "FocalMin",
    "hash": "lxKF1w",
    "neighborhood": {
      "size": 1,
      "shape": "square"
    },
    "inputs": [{
      "name": "LoadLayer",
      "hash": "NW1s9w",
      "layer_name": "us-pennsylvania-philadelphia-elevation-30m-epsg3857",
      "inputs": []
    }]
  }]
}
```

Bringing the hash right under the operation name and inputs as the last item to improve JSON readability.

### CODE REVIEW

**Comment by echeipesh** [comment]
Looking at this `function_name` is the only compound attribute we have and unnecessarily specific. Will anybody second making it either `function` or `name`?

**Comment by caseypt** [comment]
I'm down with `name`.

**Comment by echeipesh** [comment]
@jamesmcclain tested this vs multiply layer by constant case to verify parsing is correct.
Also this PR includes the switch to base32 to avoid possibility of "/" character in the hash code

**Comment by jamesmcclain** [comment]
I will review this first thing in the morning.

**Comment by jamesmcclain** [comment]
+1

**Comment by jamesmcclain** [comment]
+1

**Pull request merged**
