### PR TITLE
Adding neighborhood Class to product of Focal hashCode

### LINKED ISSUE #24: Same Output for Different Neighborhood Sizes
When we send a request for a Focal function from the front-end, like so:

```json
{
  "alias": "FocalSum",
  "inputs": [
    {
      "alias": "LocalAdd",
      "inputs": [
        {
          "layer_alias": "Landsat Red",
          "layer_name": "us-pennsylvania-philadelphia-landsat-red-30m-epsg3857",
          "name": "LoadLayer"
        },
        {
          "layer_alias": "Landsat Green",
          "layer_name": "us-pennsylvania-philadelphia-landsat-green-30m-epsg3857",
          "name": "LoadLayer"
        },
        {
          "layer_alias": "Landsat Blue",
          "layer_name": "us-pennsylvania-philadelphia-landsat-blue-30m-epsg3857",
          "name": "LoadLayer"
        }
      ],
      "name": "LocalAdd"
    }
  ],
  "name": "FocalSum",
  "neighborhood": {
    "shape": "square",
    "size": 9
  },
  "z_factor": 1
}
```

we receive a correct response:

```json
{
  "name": "FocalSum",
  "neighborhood": {
    "size": 9,
    "shape": "square"
  },
  "alias": "FocalSum",
  "hash": "CQ2IJWY",
  "inputs": [{
    "constant": null,
    "name": "LocalAdd",
    "alias": "LocalAdd",
    "hash": "2ZT3PFA",
    "inputs": [{
      "name": "LoadLayer",
      "layer_alias": "Landsat Red",
      "layer_name": "us-pennsylvania-philadelphia-landsat-red-30m-epsg3857",
      "hash": "3BWIPNI",
      "inputs": []
    }, {
      "name": "LoadLayer",
      "layer_alias": "Landsat Green",
      "layer_name": "us-pennsylvania-philadelphia-landsat-green-30m-epsg3857",
      "hash": "KRHNKAY",
      "inputs": []
    }, {
      "name": "LoadLayer",
      "layer_alias": "Landsat Blue",
      "layer_name": "us-pennsylvania-philadelphia-landsat-blue-30m-epsg3857",
      "hash": "MB3Q2YA",
      "inputs": []
    }]
  }],
  "z_factor": 1
}
```

However, if we send the same request again with a different neighborhood shape, changed from `square` above to `circle` below:

```json
{
  "alias": "FocalSum",
  "inputs": [
    {
      "alias": "LocalAdd",
      "inputs": [
        {
          "layer_alias": "Landsat Red",
          "layer_name": "us-pennsylvania-philadelphia-landsat-red-30m-epsg3857",
          "name": "LoadLayer"
        },
        {
          "layer_alias": "Landsat Green",
          "layer_name": "us-pennsylvania-philadelphia-landsat-green-30m-epsg3857",
          "name": "LoadLayer"
        },
        {
          "layer_alias": "Landsat Blue",
          "layer_name": "us-pennsylvania-philadelphia-landsat-blue-30m-epsg3857",
          "name": "LoadLayer"
        }
      ],
      "name": "LocalAdd"
    }
  ],
  "name": "FocalSum",
  "neighborhood": {
    "shape": "circle",
    "size": 9
  },
  "z_factor": 1
}
```

we receive an output identical to the first request:

```json
{
  "name": "FocalSum",
  "neighborhood": {
    "size": 9,
    "shape": "circle"
  },
  "alias": "FocalSum",
  "hash": "CQ2IJWY",
  "inputs": [{
    "constant": null,
    "name": "LocalAdd",
    "alias": "LocalAdd",
    "hash": "2ZT3PFA",
    "inputs": [{
      "name": "LoadLayer",
      "layer_alias": "Landsat Red",
      "layer_name": "us-pennsylvania-philadelphia-landsat-red-30m-epsg3857",
      "hash": "3BWIPNI",
      "inputs": []
    }, {
      "name": "LoadLayer",
      "layer_alias": "Landsat Green",
      "layer_name": "us-pennsylvania-philadelphia-landsat-green-30m-epsg3857",
      "hash": "KRHNKAY",
      "inputs": []
    }, {
      "name": "LoadLayer",
      "layer_alias": "Landsat Blue",
      "layer_name": "us-pennsylvania-philadelphia-landsat-blue-30m-epsg3857",
      "hash": "MB3Q2YA",
      "inputs": []
    }]
  }],
  "z_factor": 1
}
```

which is wrong, we should receive different output.

### PR DESCRIPTION
**Pull request by echeipesh**
fixes focal ops with different neighborhoods having the same hash
Fixes: #24

### CODE REVIEW

**Comment by jamesmcclain** [comment]
I can confirm that the hashes are now different when the neighborhood shapes are changed.

**Comment by rajadain** [comment]
When I checked out the code and ran

    $ ./sbt assembly

After downloading all dependencies I get the following compile error:

```
[info] Compiling 17 Scala sources to /Users/ttuhinanshu/dev/mlg/target/scala-2.10/classes...
[error] /Users/ttuhinanshu/dev/mlg/src/main/scala/com/azavea/modellab/NodeFormats.scala:153: type mismatch;
[error]  found   : com.azavea.modellab.WindowedReader
[error]  required: geotrellis.spark.io.FilteringLayerReader[geotrellis.spark.LayerId,geotrellis.spark.SpatialKey,geotrellis.spark.RasterRDD[geotrellis.spark.SpatialKey]]
[error]       LoadLayer(json.param[String]("layer_name"), windowedReader)
[error]                                                   ^
[error] /Users/ttuhinanshu/dev/mlg/src/main/scala/com/azavea/modellab/NodeFormats.scala:157: type mismatch;
[error]  found   : com.azavea.modellab.LoadLayer
[error]  required: com.azavea.modellab.op.Op
[error]       writeNode(o, s"LoadLayer", "layer_name" -> JsString(o.layerName)) 
[error]                 ^
[error] two errors found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 52 s, completed Nov 18, 2015 1:31:00 PM
```

**Comment by jamesmcclain** [comment]
If you haven't build this code recently, you should probably clean out your `.ivy2` cache.

**Comment by rajadain** [comment]
Ah that was probably it. Running

    $ ./sbt clean

first and then running `assembly` again seems to have fixed it.

**Comment by jamesmcclain** [comment]
That wasn't actually what I meant, but I'm glad it worked!

**Comment by rajadain** [comment]
+1 I'm now seeing separate outputs.

FocalSum with Neighborhood Size `25` and Shape `square`:

image

And with Shape `circle`:

image

**Pull request merged**
