### PR TITLE
Add New Layers

### PR DESCRIPTION
**Pull request by jamesmcclain**
Connects azavea/modellab#76

**To Test**
   * There should now be 20 total layers: the 19 listed [here](https://github.com/azavea/modellab/issues/8) (at time of writing) plus `nlcd-zoomed`.
   * Try uploading each of these files to a running instance of the modellab-geoprocessing code and verify that each can produce a tile.

### CODE REVIEW

**Comment by caseypt** [comment]
I tested that every layer loaded and that I could get tiles. The only one that I couldn't seem to get a tile with visible data was `us-pennsylvania-philadelphia-nlcd2011-trees-30m-epsg3857`. @mmcfarland Is it easy for you to verify that this dataset is valid?

**Comment by mmcfarland** [comment]
Yep, I'll take a look.

**Comment by caseypt** [comment]
@mmcfarland Thanks.

Some samples:

screen shot 2015-11-12 at 12 05 10 pm
screen shot 2015-11-12 at 12 05 16 pm
screen shot 2015-11-12 at 12 05 21 pm
screen shot 2015-11-12 at 12 05 28 pm
screen shot 2015-11-12 at 12 05 34 pm

**Comment by jamesmcclain** [comment]
> us-pennsylvania-philadelphia-nlcd2011-trees-30m-epsg3857

This tile http://localhost:8888/tms/DC2TKBY/12/1193/1551.png is a white square, but there is no error.  Probably few trees in that area.

**Comment by mmcfarland** [comment]
Here's the entire extent generated from the catalog.  I suspect @jamesmcclain is right, there simply looks like areas without a lot of canopy coverage.

screenshot from 2015-11-12 12 16 44

**Comment by caseypt** [comment]
Cool! Thanks @mmcfarland. Nice work @jamesmcclain. +1

**Comment by jamesmcclain** [comment]
Thanks for reviewing

**Pull request merged**
